### ISSUE TITLE
Doesn't work with docker container

### ISSUE THREAD

**Issue by Cally99** [nuxt/vite#172]
### Versions

nuxt-vite: 
nuxt: 

### Reproduction

run docker compose up -d

### Description

Page keeps refreshing when running in docker container.

buildModules: [
    // https://go.nuxtjs.dev/typescript
    'nuxt-vite',

  ],
  build: {
    /*
    ** Run ESLint on save
    */
    },
    vite: {
      ssr: true,
      server: {
        fs: {
          strict: false
        }
      }
    }
  }

**Comment by BobbieGoede** [comment]
I had the same issue, the page keeps refreshing because vite tries to connect to websocket on port `24678` (default) in dev mode. You need to expose the port by adding `- "24678:24678"` to ports in your compose file.

**Comment by gilesbutler** [comment]
I also had the same issue but only exposing the `24678` port didn't work for me, I also had to add the following to my Vite config...
```
server: {
    hmr: {
      protocol: 'ws',
      host: 'localhost'
    }
  },
```
Taken from https://github.com/vitejs/vite/issues/3002
Thanks for the heads up re the port though @BobbieGoede 👍

**Comment by rohrig** [comment]
I noticed with a fresh install exposing `24678` did the trick. 

However, after installing **tailwind css** the error resumed. 

Then creating a` vite.config.js` with:

`export default {
  server: {
    hmr: {
      protocol: 'ws',
      host: 'localhost'
    }
  },
}
`
got things working smoothly again. 

Thanks @BobbieGoede  and @gilesbutler

**Comment by danpastori** [comment]
We had this working through docker using @gilesbutler 's config until we updated to Nuxt 3 RC 1:

**nutxt.config.ts:**
```
  vite: {
    server: {
      hmr: {
        protocol: 'ws',
        host: 'localhost'
      }
    }
  },
```

**docker-compose.dev.yml:**
```
version: '3.8'
services:
  node:
    volumes:
      - .:/usr/src/app:cached
    networks: 
      - roast-api_development
    ports: 
      - 24678:24678
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roast.rule=Host(`roast.dev.test`)"
      - "traefik.http.routers.roast.entrypoints=websecure"
      - "traefik.http.routers.roast.tls=true"
      - "traefik.http.services.roast.loadbalancer.server.port=3000"
      - "traefik.http.services.roast.loadbalancer.server.scheme=http"
    command: "yarn dev"

networks:
  roast-api_development:
    external: true
```

Is anyone else having issues after upgrading to Nuxt 3 RC1?

**Comment by sebpalluel** [comment]
I have the same HMR issue with vite when running nuxt3 on Docker. It's reloading the page indefinitely. The port **24678** is open and the config seems right. This issue arise on both RC1 and RC2.

**nuxt.config.ts**
```ts
import { defineNuxtConfig } from 'nuxt'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
    buildModules: ['@nuxtjs/stylelint-module', '@nuxtjs/eslint-module'],
    css: ['vuetify/styles'],
    build: {
        transpile: ['vuetify', '@apollo/client', 'ts-invariant/process']
    },
    vite: {
        server: {
            hmr: {
                protocol: 'ws',
                host: 'localhost'
            }
        }
    }
})

```
**nuxt3.dockerfile**
```dockerfile
# Dockerfile
FROM node:16-alpine3.14

# create destination directory
RUN mkdir -p /usr/src/nuxt-app
WORKDIR /usr/src/nuxt-app

# update and install dependency
RUN apk update && apk upgrade
RUN apk add git

# copy the app, note .dockerignore
COPY package.json .
RUN yarn install
COPY . .
RUN yarn build

EXPOSE 3000

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

CMD [ "yarn", "dev" ]
```
**docker-compose.dev.yml**
```yaml
version: '3.9'

services:
  nuxt3:
    build:
      context: .
      dockerfile: nuxt3.dockerfile
    ports:
       - 3000:3000
       - 24678:24678
```
